### ISSUE TITLE
Object 'ESPSPI_WiFiManager' doesn't have attribure 'esp'

### ISSUE THREAD

**Issue by doraess** [adafruit/Adafruit_CircuitPython_MiniMQTT#11]
When using simple example of mqtt library, I get this error:

AttibuteError: Object 'ESPSPI_WiFiManager' doesn't have attribure 'esp'

just when connecting with the broker.

**Comment by jerryneedell** [comment]
Please post the code you are executing and describe the hardware configuration (what boards, what version of Circuitpython).

**Comment by jerryneedell** [comment]
Which example are you using? this one > https://learn.adafruit.com/mqtt-in-circuitpython/circuitpython-usage#code-usage-4-4

**Comment by doraess** [comment]
Yes, this one with different broker. No user, no password, just like this:

mqtt_client = MQTT(socket,
                   broker='nostromo.local',
                   username='',
                   password='',
                   network_manager=wifi)

**Comment by jerryneedell** [comment]
Tased on your post in another repostory, I assume this is also on your PyPortal.  Have you updated it? Both CircuitPython and the libraries?

**Comment by brentru** [comment]
@doraess  You do not have the latest version of ESP32SPI installed, `esp` has been an attribute of WiFiManager since https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/commit/54bcb5a53ad338f7b33a937ea1459b708800c2c8#diff-0e68a11e929848eefb03dcfc4cbf3497

Please head over to https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/releases to download and install the latest version of ESP32SPI.

**Comment by brentru** [comment]
Closing as issue is likely a library mis-match. Please re-open if you're still having issues.
