### ISSUE TITLE
OSError: [Errno 9] EBADF

### ISSUE THREAD

**Issue by efremovru** [adafruit/Adafruit_CircuitPython_MiniMQTT#85]
Folks, i followed the instructions ( https://learn.adafruit.com/mqtt-in-circuitpython/circuitpython-wifi-usage ) to the T and yet i can not figure out what is the reason for the error. I am using FeatherS2 and Thonny (Mu refuses to work on my machine). Here is the full printout of the results 

Connecting to Adafruit IO...
Connected to Adafruit IO! Listening for topic changes on efremovru/feeds/onoff
Sending photocell value: 0...
Traceback (most recent call last):
  File "<stdin>", line 86, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 628, in publish
OSError: [Errno 9] EBADF
 
line 86 from the "main" code is 
mqtt_client.publish(photocell_feed, photocell_val)

which of course goes to the library adafruit_minimqtt
where on line 628 i have 

self._sock.send(pub_hdr_fixed)  

which obviously is within the "publish" function

any advice will be greatly appreciated. thanks in advance!

**Comment by brentru** [comment]
Are you using the absolute latest version of both this library _and_ the CircuitPython firmware?

**Comment by efremovru** [comment]
Yes on the library, I downloaded it few days ago. I bought the FeatherS2 in March/2021. Is there a newer version of the firmware?

**Comment by FoamyGuy** [comment]
You can find the latest firmware downloads for that device here: https://circuitpython.org/board/unexpectedmaker_feathers2/

`CircuitPython 7.0.0-alpha.4` is the newest released version currently. It's still in the alpha stage, but definitely worth trying out if you are having issues and are using an older version, which is probably likely if you've never loaded a new firmware since getting the device in march 2021.

**Comment by efremovru** [comment]
OK. Will give it a try and report back.

**Comment by efremovru** [comment]
All set. Works as it should!!!
